name: Lint Commit Messages
on:
  push:
    branches:
      - '**'  # 匹配所有分支
    paths-ignore:  # 忽略特定路径，如果不设置，则所有路径的更改都会触发
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - '**'  # 匹配所有分支

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install required dependencies
        run: |
          npm install commitlint-config-wizardoc @commitlint/cli
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v6
        with:
          config: commitlint.config.js