name: Lint Commit Messages
on:
  push:
    branches:
      - '**'  # 匹配所有分支
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - '**'  # 匹配所有分支

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # 你可以指定你需要的 Node.js 版本

      - name: Install commitlint and config
        run: |
          npm install @commitlint/cli@version commitlint-config-wizardoc @version

      - name: Lint Commit Messages
        run: |
          npx commitlint --from=HEAD~1 --to=HEAD --config commitlint.config.js
