name: Lint Commit Messages
on: [pull_request]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install required dependencies
        run: |
          npm install commitlint-config-wizardoc @commitlint/cli
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v6
        with:
          config: commitlint.config.js